services:
  database:
    container_name: lost-and-found-db
    image: redis/redis-stack
    ports:
      - "5379:6379"
      - "5001:8001"
    volumes:
      - ./redis/data:/data
  api:
    container_name: lost-and-found-api
    build:
      context: ../
      dockerfile: deployments/api/Dockerfile
    ports:
      - "5080:8080"
    volumes: ['../app:/code']
    command: python manage.py runserver 0.0.0.0:8080
    environment:
      - ROOTUSERNAME=root
      - ROOTPASSWORD=cBMJ6V4HH8djT6zm
    depends_on:
      - database
  frontend:
    container_name: lost-and-found-frontend
    build:
      context: ../
      dockerfile: deployments/frontend/Dockerfile
    ports:
      - "5300:3000"
    volumes: ['../frontend:/app']
    environment:
      - NODE_ENV=${ENVIRONMENT}
    depends_on:
      - api
