import { useState } from 'react'
import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
    const [darkMode, setDarkMode] = useState(false)

    return (
        <Html>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <body className={`${darkMode ? `dark` : ``}`}>
                <Main />
                <NextScript />
            </body>
        </Html>
    )
}
