# Generated by Django 4.1.1 on 2022-09-07 21:13

import api.models.item
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.item.upload_to),
        ),
    ]
